version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ocikey_backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: turntable.proxy.rlwy.net
      DB_PORT: 24899
      DB_NAME: railway
      DB_USER: postgres
      DB_PASSWORD: CXfxBDYwgCblBScYNBRUcaZzUIhYughi
      JWT_SECRET: f054e756-2fe3-4b44-bf90-bcbd41771778
      JWT_EXPIRES_IN: 7d
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: ocikey_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    depends_on:
      - backend