version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: ocikey_postgres
    environment:
      POSTGRES_DB: ocikey_db
      POSTGRES_USER: OCI_user
      POSTGRES_PASSWORD: petoci
    ports:
      - "5000:5000"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ocikey_network

  backend:
    build: ./backend
    container_name: ocikey_backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=localhost
      - DB_PORT=5000
      - DB_NAME=ocikey_db
      - DB_USER=OCI_user
      - DB_PASSWORD=petoci
      - JWT_SECRET=f054e756-2fe3-4b44-bf90-bcbd41771778
      - JWT_EXPIRES_IN=7d
    depends_on:
      - postgres
    networks:
      - ocikey_network
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  ocikey_network:
    driver: bridge