services:
  backend:
    build: ./backend
    container_name: ocikey_backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: sub
      DB_PORT: sub
      DB_NAME: sub
      DB_USER: postgres
      DB_PASSWORD: sub
      JWT_SECRET: sub
      JWT_EXPIRES_IN: 7d
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: ocikey_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    depends_on:
      - backend
